 CREATE OR REPLACE FUNCTION FN_DOWI_ROUND(P_CCY2 VARCHAR2) RETURN NUMBER AS
 L_ROUND NUMBER;
BEGIN
  
  <<abc>>  
  BEGIN
    
SELECT CCY_DECIMALS
  INTO L_ROUND
  FROM CYTMS_CCY_DEFN_MASTER
 WHERE CCY_CODE = P_CCY2;

EXCEPTION 
 WHEN OTHERS THEN
 L_ROUND := 2;
END abc;

RETURN L_ROUND;
EXCEPTION 
WHEN OTHERS THEN
  Dbms_Output.put_line(DBMS_UTILITY.FORMAT_ERROR_STACK());
Dbms_Output.put_line(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE());
    

 END FN_DOWI_ROUND;
